#! /bin/sh

#---------------------------------------------------------------------
#                             release-ok                              
# 
# This is the opportunity for the build type to reject the creation of
# a release package.  It is intended to identify build modes which are
# acceptable for creating test packages but not acceptable for release.
#---------------------------------------------------------------------

#---------------------------------------------------------------------
#                           chicken and egg                           
#---------------------------------------------------------------------

test -f "${FW_ROOT}/share/fw/sh/fw-find.sh" && fws="${FW_ROOT}/share/fw/sh/fw-find.sh"
test -f "fw/sh/fw-find.sh" && fws="fw/sh/fw-find.sh"
test -f "fw.local/sh/fw-find.sh" && fws="fw.local/sh/fw-find.sh"
test ! -z "$fws" || {
  echo "fw-build/release-ok: fatal: can't locate fw-find.sh" 1>&2
  exit 1
}

. "$fws"

#---------------------------------------------------------------------
#                              routines                               
#---------------------------------------------------------------------

fw_source "fw-build/release-ok" "sh/fw-exec.sh"
fw_source "fw-build/release-ok" "sh/parse-args.sh"
fw_source "fw-build/release-ok" "sh/validate-args.sh"

#---------------------------------------------------------------------
#                                main                                 
#---------------------------------------------------------------------

fw_exec "build/automake/release-ok" "$@" || fatal "fw-build/release-ok"

parse_args "fw-build/release-ok" "$@"

validate_args "fw-build/release-ok" "" ""

exit 0
