#! /bin/sh

test -z "${FW_TRACE}" || set -x

touch .cvsignore
cvs -Q add .cvsignore

(
  cat .cvsignore
  for x in "$@"
    do
      echo "$x"
    done
) | perl -ne 'print $_ unless $seen{$_}++;' > .cvsignore_new

mv -f .cvsignore_new .cvsignore
